### ISSUE TITLE
First stuff to implement?

### ISSUE THREAD

**Issue by endrebak** [endrebak/TAPMAT-data#1]
Input:

> Snp list:
> 
> > SNP       Beta
> > rs501     0.51
> > rs694     0.09
> 
> Pheno values:
> 
> > CEU  51
> > TSI    105

With these data, I should look up the SNPs in the 1KG data and find the frequencies for each population. Then what?

**Comment by Deleetdk** [comment]
I wrote [a white paper](http://emilkirkegaard.dk/en/wp-content/uploads/TAPMAP_white_paper.pdf) describing what I have in mind.

Once the population-level datafile is ready, I will write the R functions and create the package.

**Comment by endrebak** [comment]
What you want me to do is to extract the population level data for the SNPs with MAF over 1% right? I suspect it will still be a lot of data.

Will look at more after work.

**Comment by endrebak** [comment]
Have begun. Hope to have the data ready within two weeks (only working a little bit on this each day).

**Comment by Deleetdk** [comment]
You may be right that it will be too much data for R to handle. We will see.

**Comment by endrebak** [comment]
I do not think it will be too much data anymore btw - I was mistaken. Reducing it to only the frequencies will be an extreme reduction in data size.

You will have to decide whether you want the data in long format or wide.

Long:

```
SNP POP VAL
rs1   CEU  0.54
rs1   TSI    0.31
...
```

Wide:

```
SNP CEU TSI
rs1   0.54   0.31
...
```

Wide takes less space, but long is often preferable according to Wickham: [Tidy Data (pdf)](http://vita.had.co.nz/papers/tidy-data.pdf)

**Comment by Deleetdk** [comment]
I prefer wide format. This is the most useful for analysis in R. Long format is useful when the data is sparse because this results in many empty cells in the wide format which increases the size. We have no empty cells, so this is not relevant.

**Comment by endrebak** [comment]
K, thanks.

There might take a few hundred mbs zipped perhaps, but this is not much for R to handle. It might be too much for cran to accept though. I'm sure we will find a solution; perhaps hosting the datafiles on gitlab or sometIng.

**Comment by endrebak** [comment]
I am going to remove all structural variants and insertions/deletions since I'm pretty sure these are not used in GWAS. If you know otherwise, please tell me.

**Comment by Deleetdk** [comment]
Just remove those, yes. GWAS only uses SNPs right now, so only include SNPs.

**Comment by endrebak** [comment]
This is what the data currently looks like:

```
endrebakkenstovner@endres-MacBook-Pro ~/c/kirkegaard> head -50 tmp/chr22.frq.strat
 CHR                                 SNP     CLST   A1   A2      MAF    MAC  NCHROBS
  22                          rs62224609      ACB    C    T 0.005208      1      192
  22                          rs62224609      ASW    C    T  0.03279      4      122
  22                          rs62224609      BEB    C    T   0.2907     50      172
  22                          rs62224609      CDX    C    T   0.1452     27      186
  22                          rs62224609      CEU    C    T   0.1162     23      198
  22                          rs62224609      CHB    C    T  0.04854     10      206
  22                          rs62224609      CHS    C    T  0.07143     15      210
  22                          rs62224609      CLM    C    T    0.117     22      188
  22                          rs62224609      ESN    C    T        0      0      198
  22                          rs62224609      FIN    C    T    0.101     20      198
  22                          rs62224609      GBR    C    T  0.07692     14      182
  22                          rs62224609      GIH    C    T   0.2816     58      206
  22                          rs62224609      GWD    C    T        0      0      226
  22                          rs62224609      IBS    C    T  0.09813     21      214
  22                          rs62224609      ITU    C    T   0.2794     57      204
  22                          rs62224609      JPT    C    T  0.09135     19      208
  22                          rs62224609      KHV    C    T  0.09596     19      198
  22                          rs62224609      LWK    C    T        0      0      198
  22                          rs62224609      MSL    C    T        0      0      170
  22                          rs62224609      MXL    C    T   0.1484     19      128
  22                          rs62224609      PEL    C    T   0.2412     41      170
  22                          rs62224609      PJL    C    T   0.2448     47      192
  22                          rs62224609      PUR    C    T  0.09135     19      208
  22                          rs62224609      STU    C    T    0.299     61      204
  22                          rs62224609      TSI    C    T  0.07477     16      214
  22                          rs62224609      YRI    C    T        0      0      216
  22                          rs62224611      ACB    C    A 0.005208      1      192
  22                          rs62224611      ASW    C    A  0.02459      3      122
  22                          rs62224611      BEB    C    A   0.2561     42      164
  22                          rs62224611      CDX    C    A   0.1183     22      186
  22                          rs62224611      CEU    C    A  0.09596     19      198
  22                          rs62224611      CHB    C    A  0.03883      8      206
  22                          rs62224611      CHS    C    A  0.06667     14      210
  22                          rs62224611      CLM    C    A   0.1011     19      188
  22                          rs62224611      ESN    C    A        0      0      198
  22                          rs62224611      FIN    C    A  0.06186     12      194
  22                          rs62224611      GBR    C    A  0.06593     12      182
  22                          rs62224611      GIH    C    A     0.23     46      200
  22                          rs62224611      GWD    C    A        0      0      226
  22                          rs62224611      IBS    C    A  0.08962     19      212
  22                          rs62224611      ITU    C    A   0.2273     45      198
  22                          rs62224611      JPT    C    A  0.07212     15      208
  22                          rs62224611      KHV    C    A  0.08081     16      198
  22                          rs62224611      LWK    C    A        0      0      198
  22                          rs62224611      MSL    C    A        0      0      170
  22                          rs62224611      MXL    C    A    0.125     16      128
  22                          rs62224611      PEL    C    A      0.2     34      170
  22                          rs62224611      PJL    C    A   0.2151     40      186
  22                          rs62224611      PUR    C    A  0.08173     17      208
...
```

I am guessing only including MAF per population is not enough. The package needs two tables: one wide df with pop mafs, and one table which shows which allele is major/minor. What do you think?

(A possible hack is to have the rownames be `rs62224609-CT`, `rs62224611-CA` etc but I think this is ugly/untidy.)

**Comment by endrebak** [comment]
IIRC:

```
NCHROBS - number of haplotypes in population (~nb. people x 2)
MAC - minor allele count
MAF is then MAC/NCHROBS
```

I dunno if NCHROBS or MAC is interesting for you when computing statistics.

**Comment by Deleetdk** [comment]
I think you should get rid of the MAC and NCHROBS columns. NCHROBS just repeats the same information over and over and inflates the filesize.

**Comment by endrebak** [comment]
I will have the files ready within 24 hours. They look like this:

```
CHR SNP A1 A2 ACB ASW BEB CDX CEU CHB CHS CLM ESN FIN GBR GIH GWD IBS ITU JPT KHV LWK MSL MXL PEL PJL PUR STU TSI YRI
21 rs1000005 G C 0.7969 0.6148 0.3547 0.2903 0.4646 0.2087 0.2952 0.4415 0.7979999999999999 0.40399999999999997 0.4121 0.3592 0.7434 0.3271 0.3333 0.27399999999999997 0.3535 0.6566 0.7941 0.4375 0.4941 0.3542 0.4615 0.3725 0.3364 0.7639
21 rs1000026 T C 0.3802 0.3852 0.3547 0.3978 0.2576 0.5291 0.4762 0.4468 0.4242 0.2323 0.3242 0.2524 0.2566 0.3458 0.3088 0.5096 0.3737 0.4394 0.3647 0.4922 0.6647 0.2708 0.3173 0.299 0.3692 0.3519
...
```

How do you want them delivered? Chromosome 21 zipped takes 7.5 mb so a conservative estimate of the whole thing gzipped will be 350 mbs (hope it will be a bit less). 

Here is a link to dropbox. If you are able to unzip and read this file I guess I'll just use dropbox.

https://www.dropbox.com/s/pbsagl8mww72z0m/chr21.csv.zip?dl=0

**Comment by Deleetdk** [comment]
It works fine for me.

I would probably prefer the data to be separated by commas instead of spaces. I think this format is more familiar to most researchers who would use this data. However, it is not a big deal. Genomic data is often space separated.

To save space, one could cut off some of the digits. Probably 4 digits will be sufficient for this.

**Comment by endrebak** [comment]
Ps. I think A1 should be the minor allele, but am not 100% certain. The [plink docs](https://www.cog-genomics.org/plink2/formats#frq_strat) say:

```
.frq.strat (cluster-stratified allele frequency report)
Produced by --freq when used with --within/--family. Not valid input for --read-freq.

A text file with a header line, and then C lines per variant (where C is the number of clusters) with the following 8-9 lines:

CHR	Chromosome code
SNP	Variant identifier
CLST	Cluster identifier
A1	Allele 1 (usually minor)
A2	Allele 2 (usually major)
MAF	Allele 1 frequency in cluster
MAC	Allele 1 count in cluster
NCHROBS	Number of allele observations in cluster
```

Is this something you can sanity check also? If not, I guess I will have to ask Chris Chang why it says mostly.

**Comment by endrebak** [comment]
Okay, I'll change to commas and four digits.

**Comment by endrebak** [comment]
Ps. you should cite:

```
http://bioinformatics.oxfordjournals.org/content/28/19/2520
http://gigascience.biomedcentral.com/articles/10.1186/s13742-015-0047-8
```

I think it will be better if you used my alias `Bertram Gilfoyle` in the paper (Very "good" (high impact) journals -> more PC, so I do not wan't to be easily linked to crimethink even though I want some credit).

Also asked about whether A1 might not be minor here: https://groups.google.com/forum/#!topic/plink2-users/IoZBzPnfWrM

**Comment by Deleetdk** [comment]
One can look up the numbers on the 1gk explorer to verify numbers. E.g.
http://browser.1000genomes.org/Homo_sapiens/Variation/Population?r=21:34432551-34433551;source=dbSNP;v=rs1000005;vdb=variation;vf=710697

So, A1 is the minor allele (G with 46%). I am assuming they use the total dataset to determine minor/major status because for some SNPs, this depends on the population. In this case G is the major allele among Africans (74%), but not everybody else. G is the ancestral variant.

I will be sure to cite the PLINK paper. :)

**Comment by endrebak** [comment]
And please do not use my name :)

**Comment by Deleetdk** [comment]
Well, you are contributing to this public repo using your own name. It may be google-able for someone dedicated. However, you are not likely to me targeted. Only those publishing the actual papers using the data will be.

**Comment by endrebak** [comment]
You are probably right. I cannot ever imagine a reviewer being cruel/dumb enough to google my name and change their opinion based on me being involved in this. Okay, use my name.

**Comment by endrebak** [comment]
Only the autosomes:

https://www.dropbox.com/s/ziwz87qsf5ljs5o/tapmat_data.zip?dl=0

I will give you chrX later, forgot about it.

**Comment by endrebak** [comment]
Note that there are SNPs just called ".". These are ones without rs ids. I dunno what you want to do with those or whether you want me to do anything about them.

**Comment by endrebak** [comment]
https://www.dropbox.com/s/f9469fiutkpg3ia/chrX.zip?dl=0

**Comment by endrebak** [comment]
You are just publishing this in openpsych, yes? I do not want to be associated with MQ (if you want to publish it there feel free to do so, just leave me out)

**Comment by Deleetdk** [comment]
Yes, I will publish in OBG if possible. We can also put it on biorxiv.

**Comment by endrebak** [comment]
You should just remove them instead of including them in the package then. They are probably variants found by 1kg that have not been given a name yet.
