### ISSUE TITLE
MAF

### ISSUE THREAD

**Issue by Deleetdk** [endrebak/TAPMAT-data#3]
Previously, I noted that most studies use a cut-off of 1% for inclusion of SNPs. However, a recent very large GWAS used a cut-off of 0.1%. Thus, we would have to lower ours as well. This probably results in a very substantial size increase of the datafile.

http://www.nature.com/mp/journal/vaop/ncurrent/full/mp201645a.html

Can you calculate versions for MAF=1% and MAF=.1% so that we can compare the sizes?

**Comment by endrebak** [comment]
Okay. Already have 1%, will do 0.01%, but tomorrow. Will remove all unnamed SNPs, which should reduce size considerably.

**Comment by endrebak** [comment]
Only 740 mbs zipped so it is twice the size of the previous file (although this one has dot-SNPs removed, reducing its size). File here: https://www.dropbox.com/s/2mui6yhjjut73af/maf_0_001.zip?dl=0

Dunno if you think this is too big for inclusion in a package. Could have it available on torrent or something.
